[package]
name = "actor-model-chat"
version = "0.1.0"
authors = ["damszew <damian.szewczyk111@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
mockall = "0.9.1"
